import type { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "mock-hydraulic-oil-68",
    name: "Hydraulic Oil 68",
    description: "Mock product for testing product search and selection.",
    basePrice: 420,
    unit: "litre",
    category: "Industrial",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-gear-oil-90",
    name: "Gear Oil 90",
    description: "Mock product for testing product search and selection.",
    basePrice: 560,
    unit: "litre",
    category: "Automotive",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-grease-nlgi-2",
    name: "Grease NLGI 2",
    description: "Mock product for testing product search and selection.",
    basePrice: 180,
    unit: "kg",
    category: "Industrial",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-engine-oil-15w40",
    name: "Engine Oil 15W40",
    description: "Mock product for testing product search and selection.",
    basePrice: 640,
    unit: "litre",
    category: "Automotive",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-atf-dexron-iii",
    name: "ATF Dexron III",
    description: "Mock product for testing product search and selection.",
    basePrice: 710,
    unit: "litre",
    category: "Automotive",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-compressor-oil-46",
    name: "Compressor Oil 46",
    description: "Mock product for testing product search and selection.",
    basePrice: 520,
    unit: "litre",
    category: "Industrial",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-turbine-oil-32",
    name: "Turbine Oil 32",
    description: "Mock product for testing product search and selection.",
    basePrice: 590,
    unit: "litre",
    category: "Industrial",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-cutting-oil-soluble",
    name: "Cutting Oil Soluble",
    description: "Mock product for testing product search and selection.",
    basePrice: 350,
    unit: "litre",
    category: "Metalworking",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-brake-fluid-dot4",
    name: "Brake Fluid DOT 4",
    description: "Mock product for testing product search and selection.",
    basePrice: 280,
    unit: "litre",
    category: "Automotive",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-coolant-concentrate",
    name: "Coolant Concentrate",
    description: "Mock product for testing product search and selection.",
    basePrice: 300,
    unit: "litre",
    category: "Automotive",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-chain-lube-spray",
    name: "Chain Lube Spray",
    description: "Mock product for testing product search and selection.",
    basePrice: 220,
    unit: "can",
    category: "Maintenance",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-rust-penetrant",
    name: "Rust Penetrant",
    description: "Mock product for testing product search and selection.",
    basePrice: 210,
    unit: "can",
    category: "Maintenance",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-white-grease-aerosol",
    name: "White Grease Aerosol",
    description: "Mock product for testing product search and selection.",
    basePrice: 260,
    unit: "can",
    category: "Maintenance",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-hydraulic-oil-46",
    name: "Hydraulic Oil 46",
    description: "Mock product for testing product search and selection.",
    basePrice: 400,
    unit: "litre",
    category: "Industrial",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "mock-hydraulic-oil-100",
    name: "Hydraulic Oil 100",
    description: "Mock product for testing product search and selection.",
    basePrice: 470,
    unit: "litre",
    category: "Industrial",
    isActive: true,
    createdAt: null,
    updatedAt: null,
  },
];
